name: Publish Image

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  deploy:
    strategy:
      matrix:
        arch: [ "ubuntu-latest" ]
        git-version: [ "2.44.0" ]
    runs-on: ${{ matrix.arch }}

    # Steps to run
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to the Docker registry
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: git.rainnny.club
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      # Publish the image
      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            git.rainnny.club/PulseApp/docs:${{ github.sha }}
            git.rainnny.club/PulseApp/docs:latest
          build-args: |
            GIT_REV=${{ gitea.sha }}